<<<<<<< HEAD
# Base plugins
=======
# BASE PLUGINS
>>>>>>> reset: git reset
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

<<<<<<< HEAD
# LSP
=======
# VIEW PLUGINS
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# INPUTS PLUGINS
>>>>>>> reset: git reset
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

<<<<<<< HEAD
# Completion
=======
>>>>>>> reset: git reset
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
<<<<<<< HEAD
repo = 'Yggdroot/indentLine'

# Quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Files
=======
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'

# FILES PLUGINS
>>>>>>> reset: git reset
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

<<<<<<< HEAD
# Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'

=======
>>>>>>> reset: git reset
# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

<<<<<<< HEAD
# CheatSheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# Themes
=======
# OTHER PLUGINS
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# THEMES
>>>>>>> reset: git reset
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'au MyAutoCmd VimEnter * nested colorscheme iceberg'
