# Base plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# lsp
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

# ale
[[plugins]]
repo = 'w0rp/ale'

# Completion
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

# syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'ujihisa/neco-look'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'

# Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'

# Quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Markdown
[[plugins]]
repo = 'iamcco/markdown-preview.vim'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# CheatSheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# Themes
[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'maksimr/Lucius2'
