# BASE PLUGINS
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# VIEW PLUGINS
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'Yggdroot/indentLine'

# INPUT PLUGINS
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

# FILE PLUGINS
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

plugins]]
repo = 'junegunn/fzf.vim'

# GIT
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# OTHER PLUGINS
[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'sheerun/vim-polyglot'

# THEMES
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'au MyAutoCmd VimEnter * nested colorscheme iceberg'
