# Base plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

# Completion
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

# Quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Files
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

# Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# CheatSheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# Themes
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'au MyAutoCmd VimEnter * nested colorscheme iceberg'
