# deoplete
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_i = 1

# LSP client
# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# on_ft = ['c', 'cpp', 'java', 'ruby', 'vue']
