# Base
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# View
[[plugins]]
repo = 'liuchengxu/eleline.vim'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Input
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'kassio/neoterm'

# File
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# Syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

# Theme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'au MyAutoCmd VimEnter * nested colorscheme iceberg'
