# Input
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = "InsertEnter"
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_add = '''
  source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_add = '''
  source ~/.config/nvim/plugins/emmet-vim.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# Syntax
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'dNitro/vim-pug-complete'
on_ft = ['pug', 'vue']
hook_add = '''
  source ~/.config/nvim/plugins/vim-pug-complete.rc.vim
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.config/nvim/plugins/vim-prettier.rc.vim
'''

# File
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
on_cmd = ['Files']

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_source = ['fzf']
