# Base
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# LSP

# View
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'ap/vim-css-color'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/vim-gitgutter.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/vim-fugitive.rc.vim
'''

# Linter
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  source ~/.config/nvim/plugins/ale.rc.vim
'''

# Syntax
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
source ~/.config/nvim/plugins/vim-vue.rc.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Theme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
